export const albums = [
  {
    AlbumNumber: 1,
    Year: 1955,
    Artist: "Frank Sinatra",
    Title: "In The Wee Small Hours",
    FavoriteSong: "",
    OneToTen: 7.5,
    Comment: "Smørsanger, deilig stemning ",
    img: "./img/1.jpg",
  },
  {
    AlbumNumber: 2,
    Year: 1956,
    Artist: "Elvis Presley",
    Title: "Elvis Presley",
    FavoriteSong: "I Got A Woman",
    OneToTen: 5.5,
    Comment: "En uskydlig Elvis",
    img: "./img/2.jpg",
  },
  {
    AlbumNumber: 3,
    Year: 1956,
    Artist: "The Louvin Brothers",
    Title: "Tragic Songs Of Life",
    FavoriteSong: "Let her Go God Bless her",
    OneToTen: 3.5,
    Comment: "Begynn å syng rent, men Mari synes det var koselig",
    img: "./img/3.jpg",
  },
  {
    AlbumNumber: 4,
    Year: 1956,
    Artist: "Louis Prima",
    Title: "The Wildest!",
    FavoriteSong: "Just a gigolo",
    OneToTen: 7.5,
    Comment: "God stemning, med innslag av humor",
    img: "./img/4.jpg",
  },
  {
    AlbumNumber: 5,
    Year: 1956,
    Artist: "Fats Domino",
    Title: "This Is Fats",
    FavoriteSong: "La-la",
    OneToTen: 6.5,
    Comment: "Tidlig Rock N roll",
    img: "./img/5.jpg",
  },
  {
    AlbumNumber: 6,
    Year: 1956,
    Artist: "Duke Ellington",
    Title: "Ellington at Newport 1956",
    FavoriteSong: "",
    OneToTen: 5,
    Comment: "Littt ensformig uten sang",
  },
  {
    AlbumNumber: 7,
    Year: 1956,
    Artist: "Frank Sinatra",
    Title: "Songs for Swingin' Lovers!",
    FavoriteSong: "",
    OneToTen: 7,
    Comment: "Klassisk Fran Sinatra",
  },
  {
    AlbumNumber: 8,
    Year: 1957,
    Artist: "The Crickets",
    Title: "The Chirping Crickets",
    FavoriteSong: "Oh Boy!",
    OneToTen: 6.5,
    Comment: "Barbershop-musikk ",
  },
  {
    AlbumNumber: 9,
    Year: 1957,
    Artist: "Count Basie",
    Title: "The Atomic Mr. Basie ",
    FavoriteSong: "Kid from the Red Bank",
    OneToTen: 6,
    Comment: "Liker stilen, men savner vokal",
  },
  {
    AlbumNumber: 10,
    Year: 1957,
    Artist: "Thelonious Monk",
    Title: "Brilliant Corners",
    FavoriteSong: "",
    OneToTen: 3,
    Comment: "Begynn å spille rent",
  },
  {
    AlbumNumber: 11,
    Year: 1957,
    Artist: "Sabu",
    Title: "Palo Congo",
    FavoriteSong: "",
    OneToTen: 4.5,
    Comment: "God stemning, men ikke noe spess",
  },
  {
    AlbumNumber: 12,
    Year: 1957,
    Artist: "Miles Davis",
    Title: "Birth of the cool",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "Fin bakgrunnsmusikk",
  },
  {
    AlbumNumber: 13,
    Year: 1957,
    Artist: "Machito",
    Title: "Kenya",
    FavoriteSong: "",
    OneToTen: 4.5,
    Comment: "Litt masete ",
  },
  {
    AlbumNumber: 14,
    Year: 1957,
    Artist: "Little Richard",
    Title: "Here's Little Richard",
    FavoriteSong: "",
    OneToTen: 7.5,
    Comment: "Får lyst til å gå på en klassisk bar",
  },
  {
    AlbumNumber: 15,
    Year: 1958,
    Artist: "Tito Puente And His Orchestra",
    Title: "Dance Mania, Vol. 1",
    FavoriteSong: "",
    OneToTen: 6.5,
    Comment: "En sigar og en Cuba Libre, takk! ",
  },
  {
    AlbumNumber: 16,
    Year: 1958,
    Artist: "Billie Holiday",
    Title: "Lady In Satin",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "Veldig fint, men litt monotont ",
  },
  {
    AlbumNumber: 17,
    Year: 1958,
    Artist: "Jack Elliot ",
    Title: "Jack Takes The Floor",
    FavoriteSong: "",
    OneToTen: 3.5,
    Comment: "Masete",
  },
  {
    AlbumNumber: 18,
    Year: 1958,
    Artist: "Sarah Vaughan",
    Title: "Sarah Vaughan At Mister Kelly's",
    FavoriteSong: "",
    OneToTen: 6,
    Comment: "Koselig, behagelig bakgrunnsmusikk",
  },
  {
    AlbumNumber: 19,
    Year: 1959,
    Artist: "Ella Fitzgerald",
    Title: "Sings The Gershwin Song Book",
    FavoriteSong: "Let's call the whole thing off",
    OneToTen: 6.5,
    Comment: "Kjempekoselig",
  },
  {
    AlbumNumber: 20,
    Year: 1959,
    Artist: "Ray Charles",
    Title: "The Genius Of Ray Charles",
    FavoriteSong: "",
    OneToTen: 7,
    Comment: "Burde høres på når man har middagsgjester",
  },
  {
    AlbumNumber: 21,
    Year: 1959,
    Artist: "Miles Davis",
    Title: "Kind Of Blue",
    FavoriteSong: "",
    OneToTen: 7,
    Comment: "Fint, men skiller seg ikke ut.",
  },
  {
    AlbumNumber: 22,
    Year: 1959,
    Artist: "Marty Robbins",
    Title: "Gunfighter Ballads And Trail Songs",
    FavoriteSong: "Billy The Kid",
    OneToTen: 7,
    Comment: "Klassisk Kountry",
  },
  {
    AlbumNumber: 23,
    Year: 1959,
    Artist: "The Dave Brubeck Quartet",
    Title: "Time Out",
    FavoriteSong: "Take Five",
    OneToTen: 7.5,
    Comment: "Deilig bakgrunnsjazz",
  },
  {
    AlbumNumber: 24,
    Year: 1960,
    Artist: "Elvis Presley",
    Title: "Elvis Is Back!",
    FavoriteSong: "Make Me Know It",
    OneToTen: 5.5,
    Comment: "Litt gjentagende, men noe bra",
  },
  {
    AlbumNumber: 25,
    Year: 1960,
    Artist: "Miriam Makeba",
    Title: "Miriam Makeba ",
    FavoriteSong: "One more dance",
    OneToTen: 6.5,
    Comment: "Feriefølelse",
  },
  {
    AlbumNumber: 26,
    Year: 1960,
    Artist: "The Everly Brothers",
    Title: "A Date With The Everly Brothers",
    FavoriteSong: "Love Hurts",
    OneToTen: 7.5,
    Comment: "Love Hurts!",
  },
  {
    AlbumNumber: 27,
    Year: 1960,
    Artist: "Jimmy Smith",
    Title: "Back At The Chicken Shack",
    FavoriteSong: "",
    OneToTen: 7,
    Comment: "Deilig jazz",
  },
  {
    AlbumNumber: 28,
    Year: 1960,
    Artist: "Muddy Waters",
    Title: "Muddy Waters At Newport",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "I got the blues",
  },
  {
    AlbumNumber: 29,
    Year: 1961,
    Artist: "Bill Evans",
    Title: "Sunday At The Village Vanguard",
    FavoriteSong: "",
    OneToTen: null,
    Comment: "",
  },
  {
    AlbumNumber: 30,
    Year: 1962,
    Artist: "Ray Charles",
    Title: "Modern Sounds In Conutry And Western Music",
    FavoriteSong: "Bye Bye Love",
    OneToTen: 7,
    Comment: "Musikk man kan høre på når man har besøk",
  },
  {
    AlbumNumber: 31,
    Year: 1962,
    Artist: "Booker T. And The M.G.s",
    Title: "Green Onions",
    FavoriteSong: "Green Onions",
    OneToTen: 5.5,
    Comment: "Musikk til kirkekaffen ",
  },
  {
    AlbumNumber: 32,
    Year: 1962,
    Artist: "Stan Getz & Charlie Byrd",
    Title: "Jazz Samba",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "Fint, men skiller seg ikke ut",
  },
  {
    AlbumNumber: 33,
    Year: 1962,
    Artist: "Ray Price",
    Title: "Night Life",
    FavoriteSong: "",
    OneToTen: null,
    Comment: "",
  },
  {
    AlbumNumber: 34,
    Year: 1963,
    Artist: "The Beatles",
    Title: "With the Beatles",
    FavoriteSong: "",
    OneToTen: null,
    Comment: "",
  },
];
