export const albums = [
  {
    AlbumNumber: 1,
    Year: 1955,
    Artist: "Frank Sinatra",
    Title: "In The Wee Small Hours",
    FavoriteSong: "",
    OneToTen: 7.5,
    Comment: "Smørsanger, deilig stemning ",
    img: "./img/1.jpg",
    Link: "https://open.spotify.com/album/3GmwKB1tgPZgXeRJZSm9WX",
  },
  {
    AlbumNumber: 2,
    Year: 1956,
    Artist: "Elvis Presley",
    Title: "Elvis Presley",
    FavoriteSong: "I Got A Woman",
    OneToTen: 5.5,
    Comment: "En uskydlig Elvis",
    img: "./img/2.jpg",
    Link: "https://open.spotify.com/album/7GXP5OhYyPVLmcVfO9Iqin",
  },
  {
    AlbumNumber: 3,
    Year: 1956,
    Artist: "The Louvin Brothers",
    Title: "Tragic Songs Of Life",
    FavoriteSong: "Let her Go God Bless her",
    OneToTen: 3.5,
    Comment: "Begynn å syng rent, men Mari synes det var koselig",
    img: "./img/3.jpg",
    Link: "https://open.spotify.com/album/5JZCCzamSeSAzsePPi632S",
  },
  {
    AlbumNumber: 4,
    Year: 1956,
    Artist: "Louis Prima",
    Title: "The Wildest!",
    FavoriteSong: "Just a gigolo",
    OneToTen: 7.5,
    Comment: "God stemning, med innslag av humor",
    img: "./img/4.jpg",
    Link: "https://open.spotify.com/album/4icS85G6VGPbFlB9UGPxct",
  },
  {
    AlbumNumber: 5,
    Year: 1956,
    Artist: "Fats Domino",
    Title: "This Is Fats",
    FavoriteSong: "La-la",
    OneToTen: 6.5,
    Comment: "Tidlig Rock N roll",
    img: "./img/5.jpg",
    Link: "https://open.spotify.com/album/3I34Fcf57TI27ZsNPqytvT",
  },
  {
    AlbumNumber: 6,
    Year: 1956,
    Artist: "Duke Ellington",
    Title: "Ellington at Newport 1956",
    FavoriteSong: "",
    OneToTen: 5,
    Comment: "Littt ensformig uten sang",
    img: "./img/6.jpg",
    Link: "https://open.spotify.com/album/4uoeNMssn5fq4boWhuwK7p",
  },
  {
    AlbumNumber: 7,
    Year: 1956,
    Artist: "Frank Sinatra",
    Title: "Songs for Swingin' Lovers!",
    FavoriteSong: "",
    OneToTen: 7,
    Comment: "Klassisk Fran Sinatra",
    img: "./img/7.jpg",
    Link: "https://open.spotify.com/album/1cyjTcGVa3GqOSFBK0EhWR",
  },
  {
    AlbumNumber: 8,
    Year: 1957,
    Artist: "The Crickets",
    Title: "The Chirping Crickets",
    FavoriteSong: "Oh Boy!",
    OneToTen: 6.5,
    Comment: "Barbershop-musikk ",
    img: "./img/8.jpg",
    Link: "https://open.spotify.com/album/1KfXNUbZrdwHMtkAGNBLBq",
  },
  {
    AlbumNumber: 9,
    Year: 1957,
    Artist: "Count Basie",
    Title: "The Atomic Mr. Basie ",
    FavoriteSong: "Kid from the Red Bank",
    OneToTen: 6,
    Comment: "Liker stilen, men savner vokal",
    img: "./img/9.jpg",
    Link: "https://open.spotify.com/album/03M3VID0s2wANlxJIJBWKb",
  },
  {
    AlbumNumber: 10,
    Year: 1957,
    Artist: "Thelonious Monk",
    Title: "Brilliant Corners",
    FavoriteSong: "",
    OneToTen: 3,
    Comment: "Begynn å spille rent",
    img: "./img/10.jpg",
    Link: "https://open.spotify.com/album/5gWF47eGSbv4BOfxoFcQtd",
  },
  {
    AlbumNumber: 11,
    Year: 1957,
    Artist: "Sabu",
    Title: "Palo Congo",
    FavoriteSong: "",
    OneToTen: 4.5,
    Comment: "God stemning, men ikke noe spess",
    img: "./img/11.jpg",
    Link: "https://open.spotify.com/album/0yPE5s2h0XF9Umc6ENEKE8",
  },
  {
    AlbumNumber: 12,
    Year: 1957,
    Artist: "Miles Davis",
    Title: "Birth of the cool",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "Fin bakgrunnsmusikk",
    img: "./img/12.jpg",
    Link: "https://open.spotify.com/album/0QWea2w5Y6pSoSWHuc7JMf",
  },
  {
    AlbumNumber: 13,
    Year: 1957,
    Artist: "Machito",
    Title: "Kenya",
    FavoriteSong: "",
    OneToTen: 4.5,
    Comment: "Litt masete ",
    img: "./img/13.jpg",
    Link: "https://open.spotify.com/album/1BHUIrORQwywRkl5cjapQz",
  },
  {
    AlbumNumber: 14,
    Year: 1957,
    Artist: "Little Richard",
    Title: "Here's Little Richard",
    FavoriteSong: "",
    OneToTen: 7.5,
    Comment: "Får lyst til å gå på en klassisk bar",
    img: "./img/14.jpg",
    Link: "https://open.spotify.com/album/4CfyfJWb1HSabAjdcLeThs",
  },
  {
    AlbumNumber: 15,
    Year: 1958,
    Artist: "Tito Puente And His Orchestra",
    Title: "Dance Mania, Vol. 1",
    FavoriteSong: "",
    OneToTen: 6.5,
    Comment: "En sigar og en Cuba Libre, takk! ",
    img: "./img/15.jpg",
    Link: "https://open.spotify.com/album/1XjabdmwipT62cLSZV45SU",
  },
  {
    AlbumNumber: 16,
    Year: 1958,
    Artist: "Billie Holiday",
    Title: "Lady In Satin",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "Veldig fint, men litt monotont ",
    img: "./img/16.jpg",
    Link: "https://open.spotify.com/album/4LrLP7DM1KBj8r2Sc098JA",
  },
  {
    AlbumNumber: 17,
    Year: 1958,
    Artist: "Jack Elliot ",
    Title: "Jack Takes The Floor",
    FavoriteSong: "",
    OneToTen: 3.5,
    Comment: "Masete",
    img: "./img/17.jpg",
    Link: "https://open.spotify.com/album/0NjGpEebiBfwAjDzyArInT",
  },
  {
    AlbumNumber: 18,
    Year: 1958,
    Artist: "Sarah Vaughan",
    Title: "Sarah Vaughan At Mister Kelly's",
    FavoriteSong: "",
    OneToTen: 6,
    Comment: "Koselig, behagelig bakgrunnsmusikk",
    img: "./img/18.jpg",
    Link: "https://open.spotify.com/album/5BkcGXQqO5jVazGGwed1C0",
  },
  {
    AlbumNumber: 19,
    Year: 1959,
    Artist: "Ella Fitzgerald",
    Title: "Sings The Gershwin Song Book",
    FavoriteSong: "Let's call the whole thing off",
    OneToTen: 6.5,
    Comment: "Kjempekoselig",
    img: "./img/19.jpg",
    Link: "https://open.spotify.com/album/2qEjBX9hxgQRXNcMFi5TKI",
  },
  {
    AlbumNumber: 20,
    Year: 1959,
    Artist: "Ray Charles",
    Title: "The Genius Of Ray Charles",
    FavoriteSong: "",
    OneToTen: 7,
    Comment: "Burde høres på når man har middagsgjester",
    img: "./img/20.jpg",
  },
  {
    AlbumNumber: 21,
    Year: 1959,
    Artist: "Miles Davis",
    Title: "Kind Of Blue",
    FavoriteSong: "",
    OneToTen: 7,
    Comment: "Fint, men skiller seg ikke ut.",
    img: "./img/21.jpg",
    Link: "https://open.spotify.com/album/4GFWnwli2cVOBp2G1zqhV1",
  },
  {
    AlbumNumber: 22,
    Year: 1959,
    Artist: "Marty Robbins",
    Title: "Gunfighter Ballads And Trail Songs",
    FavoriteSong: "Billy The Kid",
    OneToTen: 7,
    Comment: "Klassisk Kountry",
    img: "./img/22.jpg",
    Link: "https://open.spotify.com/album/3kQpBS26lAj0A0VGl1snRl",
  },
  {
    AlbumNumber: 23,
    Year: 1959,
    Artist: "The Dave Brubeck Quartet",
    Title: "Time Out",
    FavoriteSong: "Take Five",
    OneToTen: 7.5,
    Comment: "Deilig bakgrunnsjazz",
    img: "./img/23.jpg",
    Link: "https://open.spotify.com/album/0nTTEAhCZsbbeplyDMIFuA",
  },
  {
    AlbumNumber: 24,
    Year: 1960,
    Artist: "Elvis Presley",
    Title: "Elvis Is Back!",
    FavoriteSong: "Make Me Know It",
    OneToTen: 5.5,
    Comment: "Litt gjentagende, men noe bra",
    img: "./img/24.jpg",
    Link: "https://open.spotify.com/album/2SBAAtgdyjgfTO1UMHnza1",
  },
  {
    AlbumNumber: 25,
    Year: 1960,
    Artist: "Miriam Makeba",
    Title: "Miriam Makeba",
    FavoriteSong: "One more dance",
    OneToTen: 6.5,
    Comment: "Feriefølelse",
    img: "./img/25.jpg",
    Link: "https://open.spotify.com/album/1x0hxEsfIUX7NR2ovzDY8n",
  },
  {
    AlbumNumber: 26,
    Year: 1960,
    Artist: "The Everly Brothers",
    Title: "A Date With The Everly Brothers",
    FavoriteSong: "Love Hurts",
    OneToTen: 7.5,
    Comment: "Love Hurts!",
    img: "./img/26.jpg",
    Link: "https://open.spotify.com/album/4Nro0nGcWVybv8cZXmSU4P",
  },
  {
    AlbumNumber: 27,
    Year: 1960,
    Artist: "Jimmy Smith",
    Title: "Back At The Chicken Shack",
    FavoriteSong: "",
    OneToTen: 7,
    Comment: "Deilig jazz",
    img: "./img/27.jpg",
    Link: "https://open.spotify.com/album/6YhvR14clg0yibdTKB5aBv",
  },
  {
    AlbumNumber: 28,
    Year: 1960,
    Artist: "Muddy Waters",
    Title: "Muddy Waters At Newport",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "I got the blues",
    img: "./img/28.jpg",
    Link: "https://open.spotify.com/album/0Po19sRLGhou0k4FBRTjGR",
  },
  {
    AlbumNumber: 29,
    Year: 1961,
    Artist: "Bill Evans",
    Title: "Sunday At The Village Vanguard",
    FavoriteSong: "",
    OneToTen: 5,
    Comment: "Litt kjedelig",
    img: "./img/29.jpg",
    Link: "https://open.spotify.com/album/20ONXWjxrJhlX3rfNeAbS0",
  },
  {
    AlbumNumber: 30,
    Year: 1962,
    Artist: "Ray Charles",
    Title: "Modern Sounds In Conutry And Western Music",
    FavoriteSong: "Bye Bye Love",
    OneToTen: 7,
    Comment: "Musikk man kan høre på når man har besøk",
    img: "./img/30.jpg",
    Link: "https://open.spotify.com/album/4j4w5DDWMKD7ePStAl19OF",
  },
  {
    AlbumNumber: 31,
    Year: 1962,
    Artist: "Booker T. And The M.G.s",
    Title: "Green Onions",
    FavoriteSong: "Green Onions",
    OneToTen: 5.5,
    Comment: "Musikk til kirkekaffen ",
    img: "./img/31.jpg",
    Link: "https://open.spotify.com/album/2aGFVLz0oQPa3uxCfq9lcU",
  },
  {
    AlbumNumber: 32,
    Year: 1962,
    Artist: "Stan Getz & Charlie Byrd",
    Title: "Jazz Samba",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "Fint, men skiller seg ikke ut",
    img: "./img/32.jpg",
    Link: "https://open.spotify.com/album/5Lyz7ZD1UaPq6WoEqTOqom",
  },
  {
    AlbumNumber: 33,
    Year: 1962,
    Artist: "Ray Price",
    Title: "Night Life",
    FavoriteSong: "",
    OneToTen: 4.5,
    Comment: "Litt kjedelig, kunne ha blitt spilt på Valdres radio",
    img: "./img/33.jpg",
    Link: "https://open.spotify.com/album/2Y0VJl24zRlX25oILvBK36",
  },
  {
    AlbumNumber: 34,
    Year: 1963,
    Artist: "The Beatles",
    Title: "With the Beatles",
    FavoriteSong: "All My Loving",
    OneToTen: 6,
    Comment: "Klassiker, men ikke det beste av The Beatles",
    img: "./img/34.jpg",
    Link: "https://open.spotify.com/album/1aYdiJk6XKeHWGO3FzHHTr",
  },
  {
    AlbumNumber: 35,
    Year: 1963,
    Artist: "Bob Dylan",
    Title: "The Freewheelin' Bob Dylan",
    FavoriteSong: "Blowin In The Wind",
    OneToTen: 7.25,
    Comment: "Mye fint, kult med munnspill",
    img: "./img/35.jpg",
    Link: "https://open.spotify.com/album/0o1uFxZ1VTviqvNaYkTJek",
  },
  {
    AlbumNumber: 36,
    Year: 1963,
    Artist: "Phil Spector",
    Title: "A Christmas Gift For You",
    FavoriteSong: "Christmas (Baby Please Come Home)",
    OneToTen: 6,
    Comment: "Les wikipediasiden til Phil Spector",
    img: "./img/36.jpg",
    Link: "https://open.spotify.com/album/2kzkwgOFAtRsDsas5Hi0Qu",
  },
  {
    AlbumNumber: 37,
    Year: 1963,
    Artist: "Sam Cooke",
    Title: "Life At The Harlem Square Club",
    FavoriteSong: "",
    OneToTen: 6.5,
    Comment: "Festlig, noe man kan riste på knærene til",
    img: "./img/37.jpg",
    Link: "https://open.spotify.com/album/3nTXqOEHr6AfTb1WSaB4Pm",
  },
  {
    AlbumNumber: 38,
    Year: 1963,
    Artist: "Charles Mingus",
    Title: "The Black Saint And The Sinner Lady",
    FavoriteSong: "",
    OneToTen: 3,
    Comment: "Sur trompet, og bare rot",
    img: "./img/38.jpg",
    Link: "https://open.spotify.com/album/6Sts4Yh7KsDFwq2yTWrGGV",
  },
  {
    AlbumNumber: 39,
    Year: 1963,
    Artist: "James Brown",
    Title: "Live At The Apollo",
    FavoriteSong: "",
    OneToTen: 5,
    Comment: "Skilte seg ikke ut.",
    img: "./img/39.jpg",
    Link: "https://open.spotify.com/album/3vm6BtNvSuDOooTkFM54kP",
  },
  {
    AlbumNumber: 40,
    Year: 1963,
    Artist: "Stan Getz & João Gilberto",
    Title: "Getz/Gilberto",
    FavoriteSong: "",
    OneToTen: 5.5,
    Comment: "Sånn musikk jeg ville spilt hvis jeg hadde en kafe i gamlebyen",
    img: "./img/40.jpg",
    Link: "https://open.spotify.com/album/3JvFflPIx7bB6lJ4qId2Er",
  },
];
